import type { Player } from "../domain";

export const fantasyPlayers: Player[] = [
  {
    id: "p-001",
    name: "Maya Ortiz",
    club: "Northstar FC",
    position: "GK",
    price: 8,
    form: 8.9,
    color: "#d7ff4f",
    initials: "MO",
    performance: { minutes: 90, goals: 0, assists: 0, bonus: 3 },
  },
  {
    id: "p-002",
    name: "Idris Cole",
    club: "Harbor City",
    position: "DEF",
    price: 9,
    form: 7.7,
    color: "#ffb95e",
    initials: "IC",
    performance: { minutes: 90, goals: 1, assists: 0, bonus: 2 },
  },
  {
    id: "p-003",
    name: "Noah Kim",
    club: "Northstar FC",
    position: "DEF",
    price: 8,
    form: 8.2,
    color: "#a8c7ff",
    initials: "NK",
    performance: { minutes: 90, goals: 0, assists: 1, bonus: 2 },
  },
  {
    id: "p-004",
    name: "Sofia Malik",
    club: "Metro Rovers",
    position: "DEF",
    price: 7,
    form: 7.1,
    color: "#ffc8dd",
    initials: "SM",
    performance: { minutes: 72, goals: 0, assists: 0, bonus: 1 },
  },
  {
    id: "p-005",
    name: "Jules Carter",
    club: "Eastbank United",
    position: "MID",
    price: 11,
    form: 9.4,
    color: "#b8a4ff",
    initials: "JC",
    performance: { minutes: 90, goals: 1, assists: 1, bonus: 4 },
  },
  {
    id: "p-006",
    name: "Theo Laurent",
    club: "Harbor City",
    position: "MID",
    price: 10,
    form: 8.8,
    color: "#90e0ef",
    initials: "TL",
    performance: { minutes: 90, goals: 0, assists: 2, bonus: 3 },
  },
  {
    id: "p-007",
    name: "Ari Bennett",
    club: "Metro Rovers",
    position: "MID",
    price: 8,
    form: 7.9,
    color: "#f8edb7",
    initials: "AB",
    performance: { minutes: 64, goals: 1, assists: 0, bonus: 1 },
  },
  {
    id: "p-008",
    name: "Kai Okafor",
    club: "Eastbank United",
    position: "FWD",
    price: 12,
    form: 9.7,
    color: "#ff8e72",
    initials: "KO",
    performance: { minutes: 90, goals: 2, assists: 0, bonus: 5 },
  },
  {
    id: "p-009",
    name: "Lena Park",
    club: "Northstar FC",
    position: "FWD",
    price: 10,
    form: 8.6,
    color: "#9ff0c3",
    initials: "LP",
    performance: { minutes: 90, goals: 1, assists: 1, bonus: 3 },
  },
  {
    id: "p-010",
    name: "Rafael Silva",
    club: "Harbor City",
    position: "FWD",
    price: 9,
    form: 8.1,
    color: "#c4b5fd",
    initials: "RS",
    performance: { minutes: 78, goals: 1, assists: 0, bonus: 2 },
  },
];

export const demoLeaderboard = [
  { rank: 1, name: "Asterix XI", manager: "Nadia K.", points: 48, movement: "+4" },
  { rank: 2, name: "Blue District", manager: "Leon R.", points: 44, movement: "+1" },
  { rank: 3, name: "Your Clubhouse", manager: "You", points: 0, movement: "—" },
  { rank: 4, name: "Sunday Scaries", manager: "Hana M.", points: 36, movement: "-2" },
  { rank: 5, name: "The Pressers", manager: "Samir B.", points: 31, movement: "-3" },
];

export const matchdayHighlights = [
  { label: "Featured fixture", value: "Northstar FC vs. Harbor City", detail: "Tonight · 20:45" },
  { label: "Best form", value: "Kai Okafor", detail: "9.7 rating" },
  { label: "Your edge", value: "Captain pick", detail: "2× points" },
];
